jobs:

- template: .vsts-ci.Linux.yml

- job: Desktop
  variables:
    ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r15c
    ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r15c
    AndroidNdkDirectory: C:\Microsoft\AndroidNDK64\android-ndk-r15c

  pool:
    vmImage: 'windows-2022'

  workspace:
    clean: all
    
  steps:
  - checkout: self
    clean: true
    lfs: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 2.1.x
      
  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      packageType: sdk
      version: 7.0.100-rc.1.22431.12
      includePreviewVersions: true

  - template: build/canary-updater.yml
  - template: build/gitversion.yml

  - task: MSBuild@1
    inputs:
      solution: src\Uno.Playground.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:CheckExclusions=True /p:Configuration=Release /bl:$(build.artifactstagingdirectory)\build.binlog /p:AndroidSigningKeyPass=$(KeystorePassword) /p:AndroidSigningStorePass=$(KeystorePassword) 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: false
      projects: src\Uno.Playground.Api\Uno.Playground.Api.csproj
      arguments: --configuration Release --output $(Build.ArtifactStagingDirectory)/api
      zipAfterPublish: true
      modifyOutputPath: true

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
