phases:


- phase: UWP
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  queue:
    name: Default
    demands:
    - VS15.7.2

  steps:
  - checkout: self
    clean: true
    lfs: true
    
  - task: GitVersion@3
    inputs:
      updateAssemblyInfo: false

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.7.0
      checkLatest: false

  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: src\Uno.Playground.sln
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal

  - task: MSBuild@1
    displayName: 'Update version'
    inputs:
      solution: src\Build\Build.proj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: MSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: src\Uno.Playground.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)\uwp" /t:Publish "/p:Configuration=Release;Platform=x86" /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundlePlatforms="x86|x64|arm" /p:AppxBundle=Always
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Playground.WASM/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)\wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container

  - powershell: 'git clean -fdx'
    displayName: Cleanup git repo
    condition: always()

- phase: MacOS_Agent
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)/.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)/.nuget-http-cache
 
  queue:
    name: Default
    demands:
    - Agent.OS -equals Darwin
    - Xamarin.iOS -equals 11.10.1.178
 
  steps:
  - checkout: self
    clean: true
    lfs: true
 
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.3.0
      checkLatest: false
 
  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: $(Build.SourcesDirectory)/src/Uno.Playground.iOS/Uno.Playground.iOS.csproj
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal
      noCache: true
 
  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: $(Build.SourcesDirectory)/src/Build/Build.csproj
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal
      noCache: true
 
  - task: MSBuild@1
    inputs:
      solution: src/Build/build.proj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: 
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
 
  - task: MSBuild@1
    inputs:
      solution: $(Build.SourcesDirectory)/src/Uno.Playground.iOS/Uno.Playground.iOS.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:CheckExclusions=True "/p:Configuration=Release" "/p:Platform=iPhone"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false
       
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Uno.Playground.iOS/bin/iPhone/Release
      Contents: '**/*.ipa'
      TargetFolder: $(build.artifactstagingdirectory)/ios
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false
 
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: drop
      ArtifactType: Container
 
  - bash: 'git clean -fdx'
    displayName: Cleanup git repo
    condition: always()

